### ISSUE TITLE
テキストエリア内の改行が適用されていないみたいです

### ISSUE THREAD

**Issue by nasikusa** [tac0810/vue-to-php-mailer#3]
仕様でしたらすみません..。
少し気になったので、報告させていただきました。

![cap18](https://user-images.githubusercontent.com/33085596/58702445-cf93e580-83e0-11e9-95eb-b7f0fa4e2591.jpg)

![cap19](https://user-images.githubusercontent.com/33085596/58702447-d28ed600-83e0-11e9-954c-201caf67eb0f.jpg)

**Comment by tac0810** [comment]
@nasikusa 

cssをろくに当ててなかったからですね…

preタグを利用しているので、以下のようにプロパティを当てたら改行されませんか？

```css
pre {
    white-space: pre-wrap;
}
```

**Comment by nasikusa** [comment]
@tac0810 

ありがとうございます..!
解決しました。
突然issue入れてしまって、失礼しました。

**Comment by tac0810** [comment]
@nasikusa 
問題ないです！
ここのリポジトリはパブリックなので他の方も閲覧できるのでslackのDMとかで気軽に連絡してください！

**Comment by nasikusa** [comment]
@tac0810 

ありがとうございます。
すごく助かります..!
